export const features = [
  {
    key: 'defense-strategy',
    icon: '▣',
    title: '防守策略生成',
    description: '结合内部网络架构、业务部署、历史演练和安全基线生成演练防守方案。',
    mode: 'defense',
    prompt: '请基于当前资产和内部处置流程，生成攻防演练防守策略。',
  },
  {
    key: 'traffic-analysis',
    icon: '⌁',
    title: '攻击流量研判',
    description: '解析 WAF、网关、IDS、EDR 和应用日志，输出攻击类型、置信度与处置动作。',
    mode: 'defense',
    prompt: '请研判以下可疑流量，给出攻击类型、影响范围和处置建议。',
  },
  {
    key: 'incident-response',
    icon: '⚑',
    title: '应急响应编排',
    description: '按检测分析、遏制、根除、恢复、复盘生成标准化 Runbook。',
    mode: 'defense',
    prompt: '请生成一次 Web 安全事件的应急响应与处置计划。',
  },
  {
    key: 'traceback',
    icon: '◎',
    title: '溯源定位分析',
    description: '从请求链路、身份、主机、容器和数据访问角度生成证据链。',
    mode: 'defense',
    prompt: '请根据证据构建事件时间线，并输出溯源定位分析。',
  },
  {
    key: 'vulnerability',
    icon: '◇',
    title: '漏洞发现与修复',
    description: '结合资产、版本、CVE、KEV、EPSS 与内部漏洞库给出修复优先级。',
    mode: 'threat_intel',
    prompt: '请分析这些组件版本的漏洞风险，并给出修复优先级。',
  },
  {
    key: 'redteam-plan',
    icon: '△',
    title: '授权红队规划',
    description: '在授权范围内输出高层攻击面建模、验证计划和蓝队检测点。',
    mode: 'redteam',
    prompt: '请为授权攻防演练生成高层红队验证计划，不输出可武器化细节。',
  },
  {
    key: 'knowledge-rag',
    icon: '◫',
    title: 'RAG 知识库检索',
    description: '面向内部架构、业务部署、处置流程和攻防知识库进行检索增强生成。',
    mode: 'defense',
    prompt: '请基于内部知识库回答我的安全运营问题，并列出引用来源。',
  },
]
